create table if not exists products
(
    id              integer generated by default as identity
        primary key,
    created_at      timestamp        not null,
    created_by      integer,
    updated_at      timestamp        not null,
    updated_by      integer,
    category        varchar(255)     not null,
    company         varchar(255)     not null,
    count           integer          not null,
    is_in_deadline  boolean          not null,
    name            varchar(255)     not null,
    price           double precision not null,
    production_date date             not null
);

alter table products
    owner to postgres;

create table if not exists roles
(
    id   integer generated by default as identity
        primary key,
    role varchar(255)
        constraint uk_g50w4r0ru3g9uf6i6fr4kpro8
            unique
);

alter table if exists roles
    owner to postgres;

create table if not exists users
(
    id          integer generated by default as identity
        primary key,
    created_at  timestamp      not null,
    created_by  integer,
    updated_at  timestamp      not null,
    updated_by  integer,
    age         integer        not null,
    balance     numeric(19, 2) not null,
    code        varchar(255)   not null,
    email       varchar(255)   not null
        constraint uk_6dotkott2kjsp8vw4d0m25fb7
            unique,
    is_verified boolean        not null,
    lastname    varchar(255)   not null,
    name        varchar(255)   not null,
    password    varchar(255)   not null,
    username    varchar(255)   not null
        constraint uk_r43af9ap4edm43mmtq01oddj6
            unique,
    role_id     integer
        constraint fkp56c1712k691lhsyewcssf40f
            references roles
);

alter table if exists users
    owner to postgres;

